<h1>Une erreur est survenue !</h1>

<p>Une erreur est survenue, merci de vous reconnecter plus tard ou de contacter un administrateur.</p>

<h3>Détails de l'erreur</h3>
<p>N'hésitez pas à fournir le code d'erreur et le message suivant à l'administrateur :</p>
<p><strong>Code : </strong> <?=$code?></p>
<p><strong>Message : </strong><em><?=$message?></em></p>

<a href="index.php" class="special">Retour à l'accueil du site</a>
